name: Freifunk Köln, Bonn und Umgebung
wikilink: http://kbu.freifunk.net/wiki/
maplink: http://map.kbu.freifunk.net/geomap.html
markdown: redcarpet
exclude: ['publish.sh']
pygments: true
image:
    source: _assets/images/original
    output: generated
    presets:
        medium:
            width: 300
            height: 260
