name: Freifunk Köln, Bonn und Umgebung
wikilink: http://kbu.freifunk.net/
maplink: http://map.kbu.freifunk.net/
markdown: redcarpet
exclude: [publish.sh]
pygments: true
image:
    source: _assets/images/original
    output: generated
    presets:
        medium:
            width: 300
            height: 260
